apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: test-node-pool
spec:
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default 

      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["t2.medium"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-west-2a", "us-west-2b", "us-west-2c", "us-west-2d"]